### ISSUE TITLE
Failure to write to file when using sca --output-type=json --output-name=sene ./sample

### ISSUE THREAD

**Issue by rpsene** [open-power-sdk/source-code-advisor#2]
Traceback (most recent call last):
  File "/usr/local/bin/sca", line 24, in <module>
    sca.main()
  File "/usr/local/lib/python2.7/dist-packages/sca/sca.py", line 167, in main
    controller.run_sca(binary_path, binary_args, sca_options)
  File "/usr/local/lib/python2.7/dist-packages/sca/controller.py", line 76, in run_sca
    core.output_sca(group_problems, outfile, output_type)
  File "/usr/local/lib/python2.7/dist-packages/sca/core.py", line 174, in output_sca
    output_sca_json(problems_dict, outfile)
  File "/usr/local/lib/python2.7/dist-packages/sca/core.py", line 161, in output_sca_json
    outfile.write(problems_dict.get(key).to_json())
AttributeError: 'str' object has no attribute 'write'

**Comment by rgdoliveira** [comment]
@rpsene is this problem still happening? I tried to reproduce it using the same command you used and using a binary that produces SCA output and another that does not,  but it worked fine for me.

**Comment by rpsene** [comment]
@rgdoliveira what distro did you test it?

**Comment by rgdoliveira** [comment]
@rpsene I tested in an Ubuntu 16.04

**Comment by ThinkOpenly** [comment]
Closing. Preparing to archive this project.
